//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;

@Entity
@Table(name = "Address")
public class AddressEntity extends BaseEntity {
    @Enumerated(EnumType.STRING)
    protected AddressTypesEntity addrType;
    protected String mailBox;
    protected String country;
    protected String city;
    protected String postalCode;
    protected String street;
    protected String house;
    protected String room;

    /**
     * Gets the value of the addrType property.
     *
     * @return possible object is
     * {@link AddressTypesEntity }
     */
    public AddressTypesEntity getAddrType() {
        return addrType;
    }

    /**
     * Sets the value of the addrType property.
     *
     * @param value allowed object is
     *              {@link AddressTypesEntity }
     */
    public void setAddrType(AddressTypesEntity value) {
        this.addrType = value;
    }

    /**
     * Gets the value of the mailBox property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMailBox() {
        return mailBox;
    }

    /**
     * Sets the value of the mailBox property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMailBox(String value) {
        this.mailBox = value;
    }

    /**
     * Gets the value of the country property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the city property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the postalCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the street property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the house property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHouse() {
        return house;
    }

    /**
     * Sets the value of the house property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHouse(String value) {
        this.house = value;
    }

    /**
     * Gets the value of the room property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoom(String value) {
        this.room = value;
    }

}
