//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "BankDetail")
public class BankDetailEntity extends BaseEntity {


    protected String country;

    protected String bic;

    protected String swift;

    protected String checkingAccount;

    protected String accountCurrency;

    protected String bankName;

    protected String correspondentAccount;

    protected String bankAddress;

    /**
     * Gets the value of the country property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the bic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBic() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBic(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the swift property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSwift() {
        return swift;
    }

    /**
     * Sets the value of the swift property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSwift(String value) {
        this.swift = value;
    }

    /**
     * Gets the value of the checkingAccount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCheckingAccount() {
        return checkingAccount;
    }

    /**
     * Sets the value of the checkingAccount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCheckingAccount(String value) {
        this.checkingAccount = value;
    }

    /**
     * Gets the value of the accountCurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccountCurrency() {
        return accountCurrency;
    }

    /**
     * Sets the value of the accountCurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccountCurrency(String value) {
        this.accountCurrency = value;
    }

    /**
     * Gets the value of the bankName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the correspondentAccount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCorrespondentAccount() {
        return correspondentAccount;
    }

    /**
     * Sets the value of the correspondentAccount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCorrespondentAccount(String value) {
        this.correspondentAccount = value;
    }

    /**
     * Gets the value of the bankAddress property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBankAddress() {
        return bankAddress;
    }

    /**
     * Sets the value of the bankAddress property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBankAddress(String value) {
        this.bankAddress = value;
    }

}
