//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.*;
import javax.validation.constraints.Size;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;

import static javax.persistence.CascadeType.ALL;

@Entity
@Table(name = "CISTask")
public class CISTaskEntity extends BaseEntity {

    @Size(max = 100)
    protected String taskId;
    @Size(max = 100)
    protected String taskUrl;

    @Temporal(TemporalType.TIMESTAMP)
    protected Date taskDateTime;

    @OneToOne(cascade = ALL)
    protected ContractEntity contractEntity;

    /**
     * Gets the value of the taskId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * Sets the value of the taskId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTaskId(String value) {
        this.taskId = value;
    }

    /**
     * Gets the value of the taskUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTaskUrl() {
        return taskUrl;
    }

    /**
     * Sets the value of the taskUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTaskUrl(String value) {
        this.taskUrl = value;
    }

    /**
     * Gets the value of the taskDateTime property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public Date getTaskDateTime() {
        return taskDateTime;
    }

    /**
     * Sets the value of the taskDateTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setTaskDateTime(Date value) {
        this.taskDateTime = value;
    }

    /**
     * Gets the value of the contractEntity property.
     *
     * @return possible object is
     * {@link ContractEntity }
     */
    public ContractEntity getContractEntity() {
        return contractEntity;
    }

    /**
     * Sets the value of the contractEntity property.
     *
     * @param value allowed object is
     *              {@link ContractEntity }
     */
    public void setContractEntity(ContractEntity value) {
        this.contractEntity = value;
    }

}
