//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.Size;


@Entity
@Table(name = "STG_CompanyRus")
public class CompanyRusEntity extends BaseEntity {

    @Size(max = 500)
    protected String fullName;

    @Size(max = 500)
    protected String shortName;

    @Size(max = 10)
    protected String inn;

    @Size(max = 9)
    protected String kpp;

    @Size(max = 13)
    protected String ogrn;

    @Size(max = 10)
    protected String okpo;

    @Size(max = 11)
    protected String bic;

    @Size(max = 130)
    protected String asvNsiCode;

    @Size(max = 40)
    protected String sparkid;

    /**
     * Gets the value of the fullName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the shortName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the inn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kpp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKpp() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKpp(String value) {
        this.kpp = value;
    }

    /**
     * Gets the value of the ogrn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOgrn() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOgrn(String value) {
        this.ogrn = value;
    }

    /**
     * Gets the value of the okpo property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOkpo() {
        return okpo;
    }

    /**
     * Sets the value of the okpo property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOkpo(String value) {
        this.okpo = value;
    }

    /**
     * Gets the value of the bic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBic() {
        return bic;
    }

    /**
     * Sets the value of the bic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBic(String value) {
        this.bic = value;
    }

    /**
     * Gets the value of the asvNsiCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAsvNsiCode() {
        return asvNsiCode;
    }

    /**
     * Sets the value of the asvNsiCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAsvNsiCode(String value) {
        this.asvNsiCode = value;
    }

    /**
     * Gets the value of the sparkid property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSparkid() {
        return sparkid;
    }

    /**
     * Sets the value of the sparkid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSparkid(String value) {
        this.sparkid = value;
    }

}
