//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static javax.persistence.CascadeType.PERSIST;

@Entity
@Table(name = "STG_CONCUR_PROC")
public class ConcurrentProcedureEntity extends BaseEntity {


    protected String procedureNumber;

    protected String procedureStepNumber;

    protected String status;

    @Temporal(TemporalType.TIMESTAMP)
    protected Date statusDate;

    @OneToMany(cascade = PERSIST)
    protected List<OfferEntity> participatorsOfferEntities;

    /**
     * Gets the value of the procedureNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProcedureNumber() {
        return procedureNumber;
    }

    /**
     * Sets the value of the procedureNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProcedureNumber(String value) {
        this.procedureNumber = value;
    }

    /**
     * Gets the value of the procedureStepNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProcedureStepNumber() {
        return procedureStepNumber;
    }

    /**
     * Sets the value of the procedureStepNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProcedureStepNumber(String value) {
        this.procedureStepNumber = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStatusDate(Date value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the participatorsOfferEntities property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the participatorsOfferEntities property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipatorsOfferEntities().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferEntity }
     */
    public List<OfferEntity> getParticipatorsOfferEntities() {
        if (participatorsOfferEntities == null) {
            participatorsOfferEntities = new ArrayList<OfferEntity>();
        }
        return this.participatorsOfferEntities;
    }

}
