//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

//@Entity
public class ContractConclusionRequestAsyncEntity extends BaseEntity {
    protected HeaderEntity headerEntity;
    protected CISTaskEntity cisTaskEntity;

    /**
     * Gets the value of the headerEntity property.
     *
     * @return possible object is
     * {@link HeaderEntity }
     */
    public HeaderEntity getHeaderEntity() {
        return headerEntity;
    }

    /**
     * Sets the value of the headerEntity property.
     *
     * @param value allowed object is
     *              {@link HeaderEntity }
     */
    public void setHeaderEntity(HeaderEntity value) {
        this.headerEntity = value;
    }

    /**
     * Gets the value of the cisTaskEntity property.
     *
     * @return possible object is
     * {@link CISTaskEntity }
     */
    public CISTaskEntity getCisTaskEntity() {
        return cisTaskEntity;
    }

    /**
     * Sets the value of the cisTaskEntity property.
     *
     * @param value allowed object is
     *              {@link CISTaskEntity }
     */
    public void setCisTaskEntity(CISTaskEntity value) {
        this.cisTaskEntity = value;
    }

}
