//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "CounterpartyInfo")
public class CounterpartyInfoEntity extends BaseEntity {

    protected String asvnsicode;

    /**
     * Gets the value of the asvnsicode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAsvnsicode() {
        return asvnsicode;
    }

    /**
     * Sets the value of the asvnsicode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAsvnsicode(String value) {
        this.asvnsicode = value;
    }

}
