//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;


import security.contrparties.investigations.domain.CompanyForeign;
import security.contrparties.investigations.domain.CompanyRus;
import security.contrparties.investigations.domain.Counterparty;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "Counterparty")
public class CounterpartyEntity extends BaseEntity {

    @OneToOne
    protected CompanyRusEntity companyRusEntity;

    @OneToOne
    protected PrivateEntrepreneurEntity flPrivateEntrepreneurEntity;

    @OneToOne
    protected PersonRUSEntity fl;

    @OneToOne
    protected CompanyForeignEntity companyForeignEntity;

    @OneToMany
    protected List<BankDetailEntity> bankDetailEntities;

    @OneToMany
    protected List<ContactEntity> contactEntities;

    @OneToOne
    protected AttachmentEntity confirmLocation;

    @OneToOne
    protected AttachmentEntity confirmAbility;


    public CounterpartyEntity(Counterparty counterparty) {
        CompanyRus companyRus = counterparty.getCompanyRus();
        CompanyForeign companyForeign = counterparty.getCompanyForeign();

        if (companyRus != null) {
            this.companyRusEntity = new CompanyRusEntity();
            companyRusEntity.fullName = companyRus.getFullName();
            companyRusEntity.inn = companyRus.getInn();
            companyRusEntity.asvNsiCode = companyRus.getAsvNsiCode();


        } else if (companyForeign != null) {
            this.companyForeignEntity = new CompanyForeignEntity();
            companyRusEntity.fullName = companyForeignEntity.getFullName();
            companyRusEntity.asvNsiCode = companyForeignEntity.getAsvNsiCode();

        }

    }

    /**
     * Gets the value of the companyRusEntity property.
     *
     * @return possible object is
     * {@link CompanyRusEntity }
     */
    public CompanyRusEntity getCompanyRusEntity() {
        return companyRusEntity;
    }

    /**
     * Sets the value of the companyRusEntity property.
     *
     * @param value allowed object is
     *              {@link CompanyRusEntity }
     */
    public void setCompanyRusEntity(CompanyRusEntity value) {
        this.companyRusEntity = value;
    }

    /**
     * Gets the value of the flPrivateEntrepreneurEntity property.
     *
     * @return possible object is
     * {@link PrivateEntrepreneurEntity }
     */
    public PrivateEntrepreneurEntity getFlPrivateEntrepreneurEntity() {
        return flPrivateEntrepreneurEntity;
    }

    /**
     * Sets the value of the flPrivateEntrepreneurEntity property.
     *
     * @param value allowed object is
     *              {@link PrivateEntrepreneurEntity }
     */
    public void setFlPrivateEntrepreneurEntity(PrivateEntrepreneurEntity value) {
        this.flPrivateEntrepreneurEntity = value;
    }

    /**
     * Gets the value of the fl property.
     *
     * @return possible object is
     * {@link PersonRUSEntity }
     */
    public PersonRUSEntity getFl() {
        return fl;
    }

    /**
     * Sets the value of the fl property.
     *
     * @param value allowed object is
     *              {@link PersonRUSEntity }
     */
    public void setFl(PersonRUSEntity value) {
        this.fl = value;
    }

    /**
     * Gets the value of the companyForeignEntity property.
     *
     * @return possible object is
     * {@link CompanyForeignEntity }
     */
    public CompanyForeignEntity getCompanyForeignEntity() {
        return companyForeignEntity;
    }

    /**
     * Sets the value of the companyForeignEntity property.
     *
     * @param value allowed object is
     *              {@link CompanyForeignEntity }
     */
    public void setCompanyForeignEntity(CompanyForeignEntity value) {
        this.companyForeignEntity = value;
    }

    /**
     * Gets the value of the bankDetailEntities property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankDetailEntities property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankDetailEntities().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankDetailEntity }
     */
    public List<BankDetailEntity> getBankDetailEntities() {
        if (bankDetailEntities == null) {
            bankDetailEntities = new ArrayList<BankDetailEntity>();
        }
        return this.bankDetailEntities;
    }

    /**
     * Gets the value of the contactEntities property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactEntities property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactEntities().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactEntity }
     */
    public List<ContactEntity> getContactEntities() {
        if (contactEntities == null) {
            contactEntities = new ArrayList<ContactEntity>();
        }
        return this.contactEntities;
    }

    /**
     * Gets the value of the confirmLocation property.
     *
     * @return possible object is
     * {@link AttachmentEntity }
     */
    public AttachmentEntity getConfirmLocation() {
        return confirmLocation;
    }

    /**
     * Sets the value of the confirmLocation property.
     *
     * @param value allowed object is
     *              {@link AttachmentEntity }
     */
    public void setConfirmLocation(AttachmentEntity value) {
        this.confirmLocation = value;
    }

    /**
     * Gets the value of the confirmAbility property.
     *
     * @return possible object is
     * {@link AttachmentEntity }
     */
    public AttachmentEntity getConfirmAbility() {
        return confirmAbility;
    }

    /**
     * Sets the value of the confirmAbility property.
     *
     * @param value allowed object is
     *              {@link AttachmentEntity }
     */
    public void setConfirmAbility(AttachmentEntity value) {
        this.confirmAbility = value;
    }

}
