//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;


@Entity
public class HeaderEntity extends BaseEntity {


    protected long requestid;

    protected String externalsystem;

    @Temporal(TemporalType.TIMESTAMP)
    protected Date requestdate;

    @Temporal(TemporalType.TIMESTAMP)
    protected Date senddate;

    /**
     * Gets the value of the requestid property.
     */
    public long getRequestid() {
        return requestid;
    }

    /**
     * Sets the value of the requestid property.
     */
    public void setRequestid(long value) {
        this.requestid = value;
    }

    /**
     * Gets the value of the externalsystem property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getExternalsystem() {
        return externalsystem;
    }

    /**
     * Sets the value of the externalsystem property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setExternalsystem(String value) {
        this.externalsystem = value;
    }

    /**
     * Gets the value of the requestdate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public Date getRequestdate() {
        return requestdate;
    }

    /**
     * Sets the value of the requestdate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setRequestdate(Date value) {
        this.requestdate = value;
    }

    /**
     * Gets the value of the senddate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public Date getSenddate() {
        return senddate;
    }

    /**
     * Sets the value of the senddate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setSenddate(Date value) {
        this.senddate = value;
    }

}
