//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;

@Entity
@Table(name = "PersonRUS")
public class PersonRUSEntity extends BaseEntity {

    protected String firstName;

    protected String secondName;

    protected String lastName;

    protected String inn;

    protected String socialSecurityNumber;

    protected Date birthDate;

    protected String birthPlace;

    @OneToOne
    protected PassportEntity passportEntity;


    protected String asvNsiCode;

    /**
     * Gets the value of the firstName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the secondName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSecondName() {
        return secondName;
    }

    /**
     * Sets the value of the secondName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSecondName(String value) {
        this.secondName = value;
    }

    /**
     * Gets the value of the lastName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the inn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInn() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInn(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the socialSecurityNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    /**
     * Sets the value of the socialSecurityNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSocialSecurityNumber(String value) {
        this.socialSecurityNumber = value;
    }

    /**
     * Gets the value of the birthDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setBirthDate(Date value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the birthPlace property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * Sets the value of the birthPlace property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBirthPlace(String value) {
        this.birthPlace = value;
    }

    /**
     * Gets the value of the passportEntity property.
     *
     * @return possible object is
     * {@link PassportEntity }
     */
    public PassportEntity getPassportEntity() {
        return passportEntity;
    }

    /**
     * Sets the value of the passportEntity property.
     *
     * @param value allowed object is
     *              {@link PassportEntity }
     */
    public void setPassportEntity(PassportEntity value) {
        this.passportEntity = value;
    }

    /**
     * Gets the value of the asvNsiCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAsvNsiCode() {
        return asvNsiCode;
    }

    /**
     * Sets the value of the asvNsiCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAsvNsiCode(String value) {
        this.asvNsiCode = value;
    }

}
