//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;


import java.util.ArrayList;
import java.util.List;

//@Entity
public class PutHistoricalContractsEntity extends BaseEntity {

    protected HeaderEntity headerEntity;


    protected List<ContractEntity> contractEntities;

    /**
     * Gets the value of the headerEntity property.
     *
     * @return possible object is
     * {@link HeaderEntity }
     */
    public HeaderEntity getHeaderEntity() {
        return headerEntity;
    }

    /**
     * Sets the value of the headerEntity property.
     *
     * @param value allowed object is
     *              {@link HeaderEntity }
     */
    public void setHeaderEntity(HeaderEntity value) {
        this.headerEntity = value;
    }

    /**
     * Gets the value of the contractEntities property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractEntities property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractEntities().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContractEntity }
     */
    public List<ContractEntity> getContractEntities() {
        if (contractEntities == null) {
            contractEntities = new ArrayList<ContractEntity>();
        }
        return this.contractEntities;
    }

}
