//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.17 at 02:39:49 PM MSK 
//


package security.contrparties.investigations.entities;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "STG_RESPONSE")
public class SyncResponseEntity extends BaseEntity {

    protected String resultCode;

    protected String resultMessage;

    /**
     * Gets the value of the resultCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * Sets the value of the resultCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResultCode(String value) {
        this.resultCode = value;
    }

    /**
     * Gets the value of the resultMessage property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getResultMessage() {
        return resultMessage;
    }

    /**
     * Sets the value of the resultMessage property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setResultMessage(String value) {
        this.resultMessage = value;
    }

}
