//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.20 at 08:34:17 PM MSK 
//


package security.contrparties.investigations.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressTypes"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="LEGALADDR"/&gt;
 *     &lt;enumeration value="POSTADDR"/&gt;
 *     &lt;enumeration value="ACTUAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AddressTypes")
@XmlEnum
public enum AddressTypes {

    LEGALADDR,
    POSTADDR,
    ACTUAL;

    public String value() {
        return name();
    }

    public static AddressTypes fromValue(String v) {
        return valueOf(v);
    }

}
