//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.26 at 06:24:14 PM MSK 
//


package security.contrparties.investigations.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the security.contrparties.investigations.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CheckAndSaveRegistrCounterpartySRMAsync_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "CheckAndSaveRegistrCounterpartySRM_Async");
    private final static QName _CheckAndSaveRegistrCounterpartySRMAsyncResponse_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "CheckAndSaveRegistrCounterpartySRM_AsyncResponse");
    private final static QName _ConcurrentProcedureConclusionRequestAsync_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "ConcurrentProcedureConclusionRequestAsync");
    private final static QName _ConcurrentProcedureConclusionRequestAsyncResponse_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "ConcurrentProcedureConclusionRequestAsyncResponse");
    private final static QName _ContractConclusionRequestAsync_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "ContractConclusionRequestAsync");
    private final static QName _ContractConclusionRequestAsyncResponse_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "ContractConclusionRequestAsyncResponse");
    private final static QName _CounterpartySapIdentities_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "CounterpartySapIdentities");
    private final static QName _PutContractStatus_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "PutContractStatus");
    private final static QName _PutContractStatusResponse_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "PutContractStatusResponse");
    private final static QName _PutCounterpartyInfo_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "PutCounterpartyInfo");
    private final static QName _PutCounterpartyInfoResponse_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "PutCounterpartyInfoResponse");
    private final static QName _PutHistoricalContracts_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "PutHistoricalContracts");
    private final static QName _PutHistoricalContractsResponse_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "PutHistoricalContractsResponse");
    private final static QName _CisTask_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "cisTask");
    private final static QName _ConcurrentProcedure_QNAME = new QName("http://spi2.ru/jaxws/datatypes", "concurrentProcedure");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: security.contrparties.investigations.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CheckAndSaveRegistrCounterpartySRMAsync }
     * 
     */
    public CheckAndSaveRegistrCounterpartySRMAsync createCheckAndSaveRegistrCounterpartySRMAsync() {
        return new CheckAndSaveRegistrCounterpartySRMAsync();
    }

    /**
     * Create an instance of {@link CheckAndSaveRegistrCounterpartySRMAsyncResponse }
     * 
     */
    public CheckAndSaveRegistrCounterpartySRMAsyncResponse createCheckAndSaveRegistrCounterpartySRMAsyncResponse() {
        return new CheckAndSaveRegistrCounterpartySRMAsyncResponse();
    }

    /**
     * Create an instance of {@link ConcurrentProcedureConclusionRequestAsync }
     * 
     */
    public ConcurrentProcedureConclusionRequestAsync createConcurrentProcedureConclusionRequestAsync() {
        return new ConcurrentProcedureConclusionRequestAsync();
    }

    /**
     * Create an instance of {@link ConcurrentProcedureConclusionRequestAsyncResponse }
     * 
     */
    public ConcurrentProcedureConclusionRequestAsyncResponse createConcurrentProcedureConclusionRequestAsyncResponse() {
        return new ConcurrentProcedureConclusionRequestAsyncResponse();
    }

    /**
     * Create an instance of {@link ContractConclusionRequestAsync }
     * 
     */
    public ContractConclusionRequestAsync createContractConclusionRequestAsync() {
        return new ContractConclusionRequestAsync();
    }

    /**
     * Create an instance of {@link ContractConclusionRequestAsyncResponse }
     * 
     */
    public ContractConclusionRequestAsyncResponse createContractConclusionRequestAsyncResponse() {
        return new ContractConclusionRequestAsyncResponse();
    }

    /**
     * Create an instance of {@link CounterpartySapIdentities }
     * 
     */
    public CounterpartySapIdentities createCounterpartySapIdentities() {
        return new CounterpartySapIdentities();
    }

    /**
     * Create an instance of {@link PutContractStatus }
     * 
     */
    public PutContractStatus createPutContractStatus() {
        return new PutContractStatus();
    }

    /**
     * Create an instance of {@link PutContractStatusResponse }
     * 
     */
    public PutContractStatusResponse createPutContractStatusResponse() {
        return new PutContractStatusResponse();
    }

    /**
     * Create an instance of {@link PutCounterpartyInfo }
     * 
     */
    public PutCounterpartyInfo createPutCounterpartyInfo() {
        return new PutCounterpartyInfo();
    }

    /**
     * Create an instance of {@link PutCounterpartyInfoResponse }
     * 
     */
    public PutCounterpartyInfoResponse createPutCounterpartyInfoResponse() {
        return new PutCounterpartyInfoResponse();
    }

    /**
     * Create an instance of {@link PutHistoricalContracts }
     * 
     */
    public PutHistoricalContracts createPutHistoricalContracts() {
        return new PutHistoricalContracts();
    }

    /**
     * Create an instance of {@link PutHistoricalContractsResponse }
     * 
     */
    public PutHistoricalContractsResponse createPutHistoricalContractsResponse() {
        return new PutHistoricalContractsResponse();
    }

    /**
     * Create an instance of {@link CISTask }
     * 
     */
    public CISTask createCISTask() {
        return new CISTask();
    }

    /**
     * Create an instance of {@link ConcurrentProcedure }
     * 
     */
    public ConcurrentProcedure createConcurrentProcedure() {
        return new ConcurrentProcedure();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Contract }
     * 
     */
    public Contract createContract() {
        return new Contract();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link CounterpartyInfo }
     * 
     */
    public CounterpartyInfo createCounterpartyInfo() {
        return new CounterpartyInfo();
    }

    /**
     * Create an instance of {@link ContractPerson }
     * 
     */
    public ContractPerson createContractPerson() {
        return new ContractPerson();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link SyncResponse }
     * 
     */
    public SyncResponse createSyncResponse() {
        return new SyncResponse();
    }

    /**
     * Create an instance of {@link Counterparty }
     * 
     */
    public Counterparty createCounterparty() {
        return new Counterparty();
    }

    /**
     * Create an instance of {@link CompanyRus }
     * 
     */
    public CompanyRus createCompanyRus() {
        return new CompanyRus();
    }

    /**
     * Create an instance of {@link PrivateEntrepreneur }
     * 
     */
    public PrivateEntrepreneur createPrivateEntrepreneur() {
        return new PrivateEntrepreneur();
    }

    /**
     * Create an instance of {@link CompanyForeign }
     * 
     */
    public CompanyForeign createCompanyForeign() {
        return new CompanyForeign();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link BankDetail }
     * 
     */
    public BankDetail createBankDetail() {
        return new BankDetail();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAndSaveRegistrCounterpartySRMAsync }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckAndSaveRegistrCounterpartySRMAsync }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "CheckAndSaveRegistrCounterpartySRM_Async")
    public JAXBElement<CheckAndSaveRegistrCounterpartySRMAsync> createCheckAndSaveRegistrCounterpartySRMAsync(CheckAndSaveRegistrCounterpartySRMAsync value) {
        return new JAXBElement<CheckAndSaveRegistrCounterpartySRMAsync>(_CheckAndSaveRegistrCounterpartySRMAsync_QNAME, CheckAndSaveRegistrCounterpartySRMAsync.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAndSaveRegistrCounterpartySRMAsyncResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckAndSaveRegistrCounterpartySRMAsyncResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "CheckAndSaveRegistrCounterpartySRM_AsyncResponse")
    public JAXBElement<CheckAndSaveRegistrCounterpartySRMAsyncResponse> createCheckAndSaveRegistrCounterpartySRMAsyncResponse(CheckAndSaveRegistrCounterpartySRMAsyncResponse value) {
        return new JAXBElement<CheckAndSaveRegistrCounterpartySRMAsyncResponse>(_CheckAndSaveRegistrCounterpartySRMAsyncResponse_QNAME, CheckAndSaveRegistrCounterpartySRMAsyncResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConcurrentProcedureConclusionRequestAsync }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConcurrentProcedureConclusionRequestAsync }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "ConcurrentProcedureConclusionRequestAsync")
    public JAXBElement<ConcurrentProcedureConclusionRequestAsync> createConcurrentProcedureConclusionRequestAsync(ConcurrentProcedureConclusionRequestAsync value) {
        return new JAXBElement<ConcurrentProcedureConclusionRequestAsync>(_ConcurrentProcedureConclusionRequestAsync_QNAME, ConcurrentProcedureConclusionRequestAsync.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConcurrentProcedureConclusionRequestAsyncResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConcurrentProcedureConclusionRequestAsyncResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "ConcurrentProcedureConclusionRequestAsyncResponse")
    public JAXBElement<ConcurrentProcedureConclusionRequestAsyncResponse> createConcurrentProcedureConclusionRequestAsyncResponse(ConcurrentProcedureConclusionRequestAsyncResponse value) {
        return new JAXBElement<ConcurrentProcedureConclusionRequestAsyncResponse>(_ConcurrentProcedureConclusionRequestAsyncResponse_QNAME, ConcurrentProcedureConclusionRequestAsyncResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractConclusionRequestAsync }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContractConclusionRequestAsync }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "ContractConclusionRequestAsync")
    public JAXBElement<ContractConclusionRequestAsync> createContractConclusionRequestAsync(ContractConclusionRequestAsync value) {
        return new JAXBElement<ContractConclusionRequestAsync>(_ContractConclusionRequestAsync_QNAME, ContractConclusionRequestAsync.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractConclusionRequestAsyncResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ContractConclusionRequestAsyncResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "ContractConclusionRequestAsyncResponse")
    public JAXBElement<ContractConclusionRequestAsyncResponse> createContractConclusionRequestAsyncResponse(ContractConclusionRequestAsyncResponse value) {
        return new JAXBElement<ContractConclusionRequestAsyncResponse>(_ContractConclusionRequestAsyncResponse_QNAME, ContractConclusionRequestAsyncResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CounterpartySapIdentities }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CounterpartySapIdentities }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "CounterpartySapIdentities")
    public JAXBElement<CounterpartySapIdentities> createCounterpartySapIdentities(CounterpartySapIdentities value) {
        return new JAXBElement<CounterpartySapIdentities>(_CounterpartySapIdentities_QNAME, CounterpartySapIdentities.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PutContractStatus }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PutContractStatus }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "PutContractStatus")
    public JAXBElement<PutContractStatus> createPutContractStatus(PutContractStatus value) {
        return new JAXBElement<PutContractStatus>(_PutContractStatus_QNAME, PutContractStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PutContractStatusResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PutContractStatusResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "PutContractStatusResponse")
    public JAXBElement<PutContractStatusResponse> createPutContractStatusResponse(PutContractStatusResponse value) {
        return new JAXBElement<PutContractStatusResponse>(_PutContractStatusResponse_QNAME, PutContractStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PutCounterpartyInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PutCounterpartyInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "PutCounterpartyInfo")
    public JAXBElement<PutCounterpartyInfo> createPutCounterpartyInfo(PutCounterpartyInfo value) {
        return new JAXBElement<PutCounterpartyInfo>(_PutCounterpartyInfo_QNAME, PutCounterpartyInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PutCounterpartyInfoResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PutCounterpartyInfoResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "PutCounterpartyInfoResponse")
    public JAXBElement<PutCounterpartyInfoResponse> createPutCounterpartyInfoResponse(PutCounterpartyInfoResponse value) {
        return new JAXBElement<PutCounterpartyInfoResponse>(_PutCounterpartyInfoResponse_QNAME, PutCounterpartyInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PutHistoricalContracts }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PutHistoricalContracts }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "PutHistoricalContracts")
    public JAXBElement<PutHistoricalContracts> createPutHistoricalContracts(PutHistoricalContracts value) {
        return new JAXBElement<PutHistoricalContracts>(_PutHistoricalContracts_QNAME, PutHistoricalContracts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PutHistoricalContractsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PutHistoricalContractsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "PutHistoricalContractsResponse")
    public JAXBElement<PutHistoricalContractsResponse> createPutHistoricalContractsResponse(PutHistoricalContractsResponse value) {
        return new JAXBElement<PutHistoricalContractsResponse>(_PutHistoricalContractsResponse_QNAME, PutHistoricalContractsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CISTask }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CISTask }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "cisTask")
    public JAXBElement<CISTask> createCisTask(CISTask value) {
        return new JAXBElement<CISTask>(_CisTask_QNAME, CISTask.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConcurrentProcedure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ConcurrentProcedure }{@code >}
     */
    @XmlElementDecl(namespace = "http://spi2.ru/jaxws/datatypes", name = "concurrentProcedure")
    public JAXBElement<ConcurrentProcedure> createConcurrentProcedure(ConcurrentProcedure value) {
        return new JAXBElement<ConcurrentProcedure>(_ConcurrentProcedure_QNAME, ConcurrentProcedure.class, null, value);
    }

}
