//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.25 at 09:35:10 AM MSK 
//


package security.contrparties.investigations.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>Java class for Offer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Offer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sap_srm_id" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="prtcip_request_guid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="offertaAmmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Offer", propOrder = {
        "sapSrmId",
        "prtcipRequestGuid",
        "offertaAmmount"
})
public class Offer {

    @XmlElement(name = "sap_srm_id", required = true)
    protected BigDecimal sapSrmId;
    @XmlElement(name = "prtcip_request_guid", required = true)
    protected String prtcipRequestGuid;
    protected BigDecimal offertaAmmount;

    /**
     * Gets the value of the sapSrmId property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSapSrmId() {
        return sapSrmId;
    }

    /**
     * Sets the value of the sapSrmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSapSrmId(BigDecimal value) {
        this.sapSrmId = value;
    }

    /**
     * Gets the value of the prtcipRequestGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrtcipRequestGuid() {
        return prtcipRequestGuid;
    }

    /**
     * Sets the value of the prtcipRequestGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrtcipRequestGuid(String value) {
        this.prtcipRequestGuid = value;
    }

    /**
     * Gets the value of the offertaAmmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOffertaAmmount() {
        return offertaAmmount;
    }

    /**
     * Sets the value of the offertaAmmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOffertaAmmount(BigDecimal value) {
        this.offertaAmmount = value;
    }

}
