//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.21 at 11:12:19 PM MSK 
//


package security.contrparties.investigations.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PutCounterpartyInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PutCounterpartyInfo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://spi2.ru/jaxws/datatypes}Header" minOccurs="0"/&gt;
 *         &lt;element name="registrationRegrequestId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="counterparty" type="{http://spi2.ru/jaxws/datatypes}Counterparty" minOccurs="0"/&gt;
 *         &lt;element name="counterpartySapIdentities" type="{http://spi2.ru/jaxws/datatypes}CounterpartySapIdentities" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PutCounterpartyInfo", propOrder = {
    "header",
    "registrationRegrequestId",
    "counterparty",
    "counterpartySapIdentities"
})
public class PutCounterpartyInfo {

    protected Header header;
    protected String registrationRegrequestId;
    protected Counterparty counterparty;
    protected CounterpartySapIdentities counterpartySapIdentities;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the registrationRegrequestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationRegrequestId() {
        return registrationRegrequestId;
    }

    /**
     * Sets the value of the registrationRegrequestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationRegrequestId(String value) {
        this.registrationRegrequestId = value;
    }

    /**
     * Gets the value of the counterparty property.
     * 
     * @return
     *     possible object is
     *     {@link Counterparty }
     *     
     */
    public Counterparty getCounterparty() {
        return counterparty;
    }

    /**
     * Sets the value of the counterparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Counterparty }
     *     
     */
    public void setCounterparty(Counterparty value) {
        this.counterparty = value;
    }

    /**
     * Gets the value of the counterpartySapIdentities property.
     * 
     * @return
     *     possible object is
     *     {@link CounterpartySapIdentities }
     *     
     */
    public CounterpartySapIdentities getCounterpartySapIdentities() {
        return counterpartySapIdentities;
    }

    /**
     * Sets the value of the counterpartySapIdentities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CounterpartySapIdentities }
     *     
     */
    public void setCounterpartySapIdentities(CounterpartySapIdentities value) {
        this.counterpartySapIdentities = value;
    }

}
